### PR TITLE
added python3 support

### PR DESCRIPTION
**Pull request by mjhea0**

### CODE REVIEW

**Comment by nghenglim** [comment]
While Adding python 3 support, I want to maintain python 2 support as well since it is still default python in Linux distro.

To add python 3 compatible, I will prefer to follow what tensorflow do by adding from `__future__ import print_function` etc

**Comment by mjhea0** [comment]
The code is Python 2.7 compatible as well.

**Comment by nghenglim** [comment]
True, I've made some changes just now. Will merge it after conflicts is resolved.

**Comment by mjhea0** [comment]
updated. ready to merge!

**Pull request merged**
